name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check out code
      uses: actions/checkout@v4
      with:
        repository: 'ahui2016/temp-files'
        path: 'app'

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: amgascool/gofile:latest
        file: ./Dockerfile
